compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

supportedArchitectures:
  os:
    - current
    - linux
    - darwin
    - win32
  cpu:
    - current
    - arm64
    - x64

yarnPath: .yarn/releases/yarn-4.8.1.cjs
